#!/usr/bin/env ts-node
/**
 * Soroban contract binding generator.
 *
 * For each contract alias registered in contracts/registry.json, fetches the
 * on-chain contract spec from the configured RPC endpoint and emits typed
 * TypeScript bindings into packages/sdk/src/generated/<alias>.ts.
 *
 * The generated files embed a pinned SPEC_HASH (SHA-256 of the raw XDR spec)
 * so that any subsequent drift—spec changed without re-running this script—
 * surfaces immediately at VaultClient construction time via SpecMismatchError.
 *
 * Exit codes:
 *   0 — all bindings generated successfully
 *   1 — one or more contracts failed; errors printed to stderr
 *   2 — --check mode detected drift; human-readable diff written to stdout
 */

import fs from 'fs';
import path from 'path';
import { execSync, spawnSync } from 'child_process';
import { createHash } from 'crypto';

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const REPO_ROOT = path.resolve(__dirname, '..');
const REGISTRY_PATH = path.join(REPO_ROOT, 'contracts', 'registry.json');
const OUTPUT_DIR = path.join(REPO_ROOT, 'packages', 'sdk', 'src', 'generated');
const STELLAR_CLI = process.env.STELLAR_CLI_BIN ?? 'stellar';

const DEFAULT_NETWORK = (process.env.STELLAR_NETWORK ?? 'testnet') as 'testnet' | 'mainnet' | 'local';
const DEFAULT_RPC_URL =
  process.env.SOROBAN_RPC_URL ??
  (DEFAULT_NETWORK === 'mainnet'
    ? 'https://soroban-mainnet.stellar.org'
    : 'https://soroban-testnet.stellar.org');

interface RegistryEntry {
  contractId: string;
  alias: string;
  specHash?: string;
}

type Registry = Record<string, Record<string, string>>;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sha256(data: string): string {
  return createHash('sha256').update(data).digest('hex');
}

function loadRegistry(): Record<string, RegistryEntry> {
  if (!fs.existsSync(REGISTRY_PATH)) {
    throw new Error(`Registry not found at ${REGISTRY_PATH}`);
  }
  const raw: Registry = JSON.parse(fs.readFileSync(REGISTRY_PATH, 'utf-8'));
  const network = raw[DEFAULT_NETWORK];
  if (!network) {
    throw new Error(`No entries for network "${DEFAULT_NETWORK}" in registry.json`);
  }
  return Object.fromEntries(
    Object.entries(network).map(([alias, contractId]) => [alias, { alias, contractId }]),
  );
}

function fetchSpecXdr(contractId: string, rpcUrl: string): string {
  const result = spawnSync(
    STELLAR_CLI,
    ['contract', 'fetch', '--id', contractId, '--rpc-url', rpcUrl, '--output', 'xdr'],
    { encoding: 'utf-8' },
  );
  if (result.status !== 0) {
    throw new Error(
      `stellar contract fetch failed for ${contractId}:\n${result.stderr ?? result.stdout}`,
    );
  }
  return result.stdout.trim();
}

function generateBindingsSource(
  alias: string,
  contractId: string,
  specXdr: string,
  specHash: string,
  network: string,
): string {
  const constantName = `${alias.toUpperCase().replace(/-/g, '_')}_SPEC_HASH`;
  const clientName = `${alias.replace(/(^|-)\w/g, (m) => m.replace('-', '').toUpperCase())}Client`;

  return `/**
 * AUTOGENERATED SOROBAN CONTRACT BINDINGS FOR ${alias.toUpperCase()}
 *
 * DO NOT EDIT DIRECTLY.
 * Contract Alias: ${alias}
 * Contract ID: ${contractId}
 * Network: ${network}
 * Pinned Spec Hash: ${specHash}
 * Generated At: ${new Date().toISOString()}
 */

export const ${constantName} = "${specHash}";

export const CONTRACT_ALIAS = "${alias}" as const;
export const CONTRACT_ID = "${contractId}" as const;

export { ${constantName} as SPEC_HASH };

// Raw spec XDR (base64) for on-chain verification.
export const SPEC_XDR = "${specXdr}";
`;
}

// ---------------------------------------------------------------------------
// Drift check (--check mode)
// ---------------------------------------------------------------------------

function checkDrift(entries: Record<string, RegistryEntry>, rpcUrl: string): boolean {
  let hasDrift = false;
  for (const [alias, entry] of Object.entries(entries)) {
    const outFile = path.join(OUTPUT_DIR, `${alias}.ts`);
    if (!fs.existsSync(outFile)) {
      console.log(`[DRIFT] ${alias}: generated file missing (${outFile})`);
      hasDrift = true;
      continue;
    }
    try {
      const specXdr = fetchSpecXdr(entry.contractId, rpcUrl);
      const liveHash = sha256(specXdr);
      const existing = fs.readFileSync(outFile, 'utf-8');
      const hashMatch = existing.match(/Pinned Spec Hash: ([a-f0-9]{64})/);
      if (!hashMatch) {
        console.log(`[DRIFT] ${alias}: no pinned hash found in generated file`);
        hasDrift = true;
        continue;
      }
      if (hashMatch[1] !== liveHash) {
        console.log(`[DRIFT] ${alias}: hash mismatch`);
        console.log(`  Pinned : ${hashMatch[1]}`);
        console.log(`  Live   : ${liveHash}`);
        hasDrift = true;
      } else {
        console.log(`[OK]    ${alias}: hash matches (${liveHash.slice(0, 12)}...)`);
      }
    } catch (err) {
      console.error(`[ERROR] ${alias}: ${(err as Error).message}`);
      hasDrift = true;
    }
  }
  return hasDrift;
}

// ---------------------------------------------------------------------------
// Generate mode
// ---------------------------------------------------------------------------

function generateAll(
  entries: Record<string, RegistryEntry>,
  rpcUrl: string,
): { ok: string[]; failed: string[] } {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });

  const ok: string[] = [];
  const failed: string[] = [];

  for (const [alias, entry] of Object.entries(entries)) {
    try {
      console.log(`Generating bindings for ${alias} (${entry.contractId})...`);
      const specXdr = fetchSpecXdr(entry.contractId, rpcUrl);
      const specHash = sha256(specXdr);
      const source = generateBindingsSource(alias, entry.contractId, specXdr, specHash, DEFAULT_NETWORK);
      const outFile = path.join(OUTPUT_DIR, `${alias}.ts`);
      fs.writeFileSync(outFile, source, 'utf-8');
      console.log(`  -> ${path.relative(REPO_ROOT, outFile)} (hash: ${specHash.slice(0, 12)}...)`);
      ok.push(alias);
    } catch (err) {
      console.error(`  FAILED ${alias}: ${(err as Error).message}`);
      failed.push(alias);
    }
  }

  return { ok, failed };
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

const CHECK_MODE = process.argv.includes('--check');
const rpcUrl = process.argv.find((a) => a.startsWith('--rpc-url='))?.split('=')[1] ?? DEFAULT_RPC_URL;

let exitCode = 0;

try {
  const entries = loadRegistry();

  if (CHECK_MODE) {
    console.log(`Checking binding drift against ${rpcUrl} (network: ${DEFAULT_NETWORK})\n`);
    const hasDrift = checkDrift(entries, rpcUrl);
    exitCode = hasDrift ? 2 : 0;
  } else {
    console.log(`Generating bindings from ${rpcUrl} (network: ${DEFAULT_NETWORK})\n`);
    const { ok, failed } = generateAll(entries, rpcUrl);
    console.log(`\nDone. Generated: ${ok.length} | Failed: ${failed.length}`);
    exitCode = failed.length > 0 ? 1 : 0;
  }
} catch (err) {
  console.error(`Fatal: ${(err as Error).message}`);
  exitCode = 1;
}

process.exit(exitCode);
